/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saniy
 */
import javax.swing.*;
import java.awt.*;
public class AboutScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AboutScreen.class.getName());

    /**
     * Creates new form AboutScreen
     */
    public AboutScreen() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void setupUI() {
        setTitle("About Green Ledger");
        setSize(450, 400);
        setLocationRelativeTo(null);
        setLayout(null);
        getContentPane().setBackground(new Color(34, 139, 34));

        // Logo
        JLabel logo = new JLabel("🌱");
        logo.setFont(new Font("Arial", Font.PLAIN, 60));
        logo.setBounds(180, 20, 100, 70);
        add(logo);

        // White panel
        JPanel panel = new JPanel();
        panel.setBounds(40, 100, 360, 250);
        panel.setLayout(null);
        panel.setBackground(Color.WHITE);
        add(panel);

        JLabel title = new JLabel("GREEN LEDGER v1.0");
        title.setFont(new Font("Arial", Font.BOLD, 18));
        title.setForeground(new Color(34, 139, 34));
        title.setBounds(70, 15, 280, 30);
        panel.add(title);

        JLabel desc = new JLabel("<html><center>A transparent subsidy management<br>system for rural afforestation.<br>Prevents fraud in government<br>subsidy distribution.</center></html>");
        desc.setFont(new Font("Arial", Font.PLAIN, 13));
        desc.setBounds(50, 50, 280, 80);
        panel.add(desc);

        JLabel dev = new JLabel("Developed by: Saniya");
        dev.setFont(new Font("Arial", Font.BOLD, 13));
        dev.setBounds(90, 140, 250, 25);
        panel.add(dev);

        JLabel college = new JLabel("Vasavi College of Engineering");
        college.setFont(new Font("Arial", Font.PLAIN, 12));
        college.setBounds(75, 165, 250, 25);
        panel.add(college);

        JLabel year = new JLabel("B.Tech IT | 2024-25");
        year.setFont(new Font("Arial", Font.PLAIN, 12));
        year.setBounds(120, 190, 200, 25);
        panel.add(year);

        JButton btnClose = new JButton("Close");
        btnClose.setBounds(150, 220, 100, 30);
        btnClose.setBackground(new Color(34, 139, 34));
        btnClose.setForeground(Color.WHITE);
        btnClose.addActionListener(e -> dispose());
        panel.add(btnClose);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AboutScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
