/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saniy
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
public class AuditLogScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuditLogScreen.class.getName());

    /**
     * Creates new form AuditLogScreen
     */
    public AuditLogScreen() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void setupUI() {
        setTitle("Audit Log - System Activities");
        setSize(900, 550);
        setLocationRelativeTo(null);
        setLayout(null);
        getContentPane().setBackground(new Color(240, 255, 240));

        JLabel title = new JLabel("📋 System Audit Log - All Database Changes");
        title.setFont(new Font("Arial", Font.BOLD, 22));
        title.setBounds(200, 15, 500, 40);
        add(title);

        JLabel subtitle = new JLabel("Automatically recorded via database triggers on Insert/Update/Delete operations");
        subtitle.setFont(new Font("Arial", Font.ITALIC, 12));
        subtitle.setBounds(120, 55, 700, 25);
        add(subtitle);

        String[] columns = {"Log ID", "Action", "Table", "Record ID", "Details", "Timestamp"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Read-only table
            }
        };

        try {
            java.sql.Connection con = DBConnection.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "❌ Database connection failed!");
                return;
            }

            String sql = "SELECT log_id, action, table_name, record_id, SUBSTRING(new_value, 1, 50) as details, action_timestamp " +
                        "FROM AuditLog ORDER BY action_timestamp DESC LIMIT 150";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            int count = 0;
            while (rs.next()) {
                count++;
                Object[] row = {
                    rs.getInt("log_id"),
                    rs.getString("action"),
                    rs.getString("table_name"),
                    rs.getInt("record_id"),
                    rs.getString("details"),
                    rs.getTimestamp("action_timestamp")
                };
                model.addRow(row);
            }

            if (model.getRowCount() == 0) {
                Object[] row = {"-", "System Ready", "-", "-", "Database initialized with triggers", java.time.LocalDateTime.now()};
                model.addRow(row);
            }

            con.close();
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading audit log", e);
            JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
        }

        JTable table = new JTable(model);
        table.setRowHeight(25);
        table.getTableHeader().setBackground(new Color(34, 139, 34));
        table.getTableHeader().setForeground(Color.WHITE);
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                table.clearSelection();
            }
        });

        JScrollPane scroll = new JScrollPane(table);
        scroll.setBounds(20, 90, 860, 380);
        add(scroll);

        // Bottom stats panel
        JPanel statsPanel = new JPanel();
        statsPanel.setBounds(20, 480, 860, 50);
        statsPanel.setLayout(null);
        statsPanel.setBackground(new Color(200, 240, 200));
        statsPanel.setBorder(BorderFactory.createLineBorder(new Color(34, 139, 34), 2));
        add(statsPanel);

        JLabel statsLabel1 = new JLabel("✓ Active Triggers: Tree (3), Farmer (2), Subsidy (1), Fraud Detection (3)");
        statsLabel1.setFont(new Font("Arial", Font.BOLD, 11));
        statsLabel1.setBounds(10, 5, 840, 18);
        statsPanel.add(statsLabel1);

        JLabel statsLabel2 = new JLabel("• Operations logged: INSERT, UPDATE, DELETE | Latest 150 entries shown");
        statsLabel2.setFont(new Font("Arial", Font.PLAIN, 10));
        statsLabel2.setBounds(10, 25, 840, 18);
        statsPanel.add(statsLabel2);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuditLogScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
