/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saniy
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
public class UpdateDelete extends javax.swing.JFrame {
    JTextField searchField;
    JTable table;
    DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateDelete.class.getName());

    /**
     * Creates new form UpdateDelete
     */
    public UpdateDelete() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void setupUI() {
        setTitle("✏️ Update / Delete Farmer Records");
        setSize(950, 680);
        setLocationRelativeTo(null);
        setLayout(null);
        getContentPane().setBackground(new Color(245, 250, 245));

        // ===== HEADER PANEL =====
        JPanel headerPanel = new JPanel();
        headerPanel.setBounds(0, 0, 950, 80);
        headerPanel.setBackground(new Color(34, 100, 34));
        headerPanel.setLayout(null);
        add(headerPanel);

        JLabel headerTitle = new JLabel("✏️ Manage Farmer Records");
        headerTitle.setFont(new Font("Arial", Font.BOLD, 24));
        headerTitle.setForeground(Color.WHITE);
        headerTitle.setBounds(20, 10, 400, 30);
        headerPanel.add(headerTitle);

        JLabel headerSubtitle = new JLabel("Search, update, or delete farmer information");
        headerSubtitle.setFont(new Font("Arial", Font.ITALIC, 12));
        headerSubtitle.setForeground(new Color(200, 255, 200));
        headerSubtitle.setBounds(20, 45, 400, 25);
        headerPanel.add(headerSubtitle);

        // ===== SEARCH PANEL =====
        JPanel searchPanel = new JPanel();
        searchPanel.setBounds(20, 90, 910, 70);
        searchPanel.setBackground(Color.WHITE);
        searchPanel.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 2));
        searchPanel.setLayout(null);
        add(searchPanel);

        JLabel lbl = new JLabel("🔍 Search by Farmer ID:");
        lbl.setFont(new Font("Arial", Font.BOLD, 13));
        lbl.setForeground(new Color(34, 80, 34));
        lbl.setBounds(20, 15, 180, 25);
        searchPanel.add(lbl);

        searchField = new JTextField();
        searchField.setBounds(210, 15, 180, 30);
        searchField.setFont(new Font("Arial", Font.PLAIN, 13));
        searchField.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(150, 150, 150), 1),
            BorderFactory.createEmptyBorder(5, 8, 5, 8)
        ));
        searchPanel.add(searchField);

        JButton btnSearch = new JButton("🔎 Search");
        btnSearch.setBounds(405, 15, 100, 30);
        btnSearch.setBackground(new Color(34, 139, 34));
        btnSearch.setForeground(Color.WHITE);
        btnSearch.setFont(new Font("Arial", Font.BOLD, 12));
        btnSearch.setFocusPainted(false);
        btnSearch.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnSearch.addActionListener(e -> searchFarmer());
        searchPanel.add(btnSearch);

        JButton btnRefresh = new JButton("🔄 Reset");
        btnRefresh.setBounds(520, 15, 100, 30);
        btnRefresh.setBackground(new Color(100, 100, 100));
        btnRefresh.setForeground(Color.WHITE);
        btnRefresh.setFont(new Font("Arial", Font.BOLD, 12));
        btnRefresh.setFocusPainted(false);
        btnRefresh.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(e -> {
            searchField.setText("");
            model.setRowCount(0);
        });
        searchPanel.add(btnRefresh);

        JLabel statusLabel = new JLabel("Status: Ready");
        statusLabel.setFont(new Font("Arial", Font.ITALIC, 11));
        statusLabel.setForeground(new Color(100, 100, 100));
        statusLabel.setBounds(650, 20, 230, 20);
        searchPanel.add(statusLabel);

        // ===== TABLE PANEL =====
        JPanel tablePanel = new JPanel();
        tablePanel.setBounds(20, 170, 910, 350);
        tablePanel.setBackground(Color.WHITE);
        tablePanel.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 2));
        tablePanel.setLayout(new BorderLayout());
        add(tablePanel);

        String[] columns = {"Farmer ID", "Name", "Village", "Aadhaar", "Phone", "Email"};
        model = new DefaultTableModel(columns, 0) {
            public boolean isCellEditable(int row, int col) {
                return col != 0; // Farmer ID not editable
            }
        };

        table = new JTable(model);
        table.setRowHeight(25);
        table.getTableHeader().setBackground(new Color(34, 139, 34));
        table.getTableHeader().setForeground(Color.WHITE);
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        table.setFont(new Font("Arial", Font.PLAIN, 11));
        table.setSelectionBackground(new Color(184, 207, 229));
        table.setSelectionForeground(Color.BLACK);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        JScrollPane scroll = new JScrollPane(table);
        tablePanel.add(scroll, BorderLayout.CENTER);

        // ===== ACTION BUTTONS PANEL =====
        JPanel actionPanel = new JPanel();
        actionPanel.setBounds(20, 530, 910, 60);
        actionPanel.setBackground(new Color(240, 245, 240));
        actionPanel.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1));
        actionPanel.setLayout(null);
        add(actionPanel);

        JLabel actionLabel = new JLabel("📋 Select a row and choose action:");
        actionLabel.setFont(new Font("Arial", Font.BOLD, 12));
        actionLabel.setForeground(new Color(34, 80, 34));
        actionLabel.setBounds(20, 8, 300, 20);
        actionPanel.add(actionLabel);

        JButton btnUpdate = new JButton("✏️ Update Record");
        btnUpdate.setBounds(320, 8, 140, 35);
        btnUpdate.setBackground(new Color(0, 100, 200));
        btnUpdate.setForeground(Color.WHITE);
        btnUpdate.setFont(new Font("Arial", Font.BOLD, 11));
        btnUpdate.setFocusPainted(false);
        btnUpdate.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(e -> updateRecord());
        actionPanel.add(btnUpdate);

        JButton btnDelete = new JButton("🗑️ Delete Record");
        btnDelete.setBounds(475, 8, 140, 35);
        btnDelete.setBackground(new Color(200, 0, 0));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFont(new Font("Arial", Font.BOLD, 11));
        btnDelete.setFocusPainted(false);
        btnDelete.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDelete.addActionListener(e -> deleteRecord());
        actionPanel.add(btnDelete);

        JButton btnViewDetails = new JButton("👁️ View Details");
        btnViewDetails.setBounds(630, 8, 140, 35);
        btnViewDetails.setBackground(new Color(100, 100, 0));
        btnViewDetails.setForeground(Color.WHITE);
        btnViewDetails.setFont(new Font("Arial", Font.BOLD, 11));
        btnViewDetails.setFocusPainted(false);
        btnViewDetails.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnViewDetails.addActionListener(e -> viewDetails());
        actionPanel.add(btnViewDetails);

        JButton btnClose = new JButton("❌ Close");
        btnClose.setBounds(785, 8, 100, 35);
        btnClose.setBackground(new Color(100, 100, 100));
        btnClose.setForeground(Color.WHITE);
        btnClose.setFont(new Font("Arial", Font.BOLD, 11));
        btnClose.setFocusPainted(false);
        btnClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClose.addActionListener(e -> dispose());
        actionPanel.add(btnClose);
    }

    private void searchFarmer() {
        String farmerIdText = searchField.getText().trim();
        if (farmerIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Farmer ID!");
            return;
        }

        model.setRowCount(0);

        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM Farmer WHERE farmer_id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(farmerIdText));
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Object[] row = {
                    rs.getInt("farmer_id"),
                    rs.getString("name"),
                    rs.getString("village"),
                    rs.getString("aadhaar_no"),
                    rs.getString("phone")
                };
                model.addRow(row);
            } else {
                JOptionPane.showMessageDialog(this, "Farmer not found!");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void updateFarmer() {
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Search for a farmer first!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to update this record?",
            "Confirm Update", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            int farmerId = (int) model.getValueAt(0, 0);
            String name = model.getValueAt(0, 1).toString();
            String village = model.getValueAt(0, 2).toString();
            String aadhaar = model.getValueAt(0, 3).toString();
            String phone = model.getValueAt(0, 4).toString();

            Connection con = DBConnection.getConnection();
            String sql = "UPDATE Farmer SET name=?, village=?, aadhaar_no=?, phone=? WHERE farmer_id=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, name);
            ps.setString(2, village);
            ps.setString(3, aadhaar);
            ps.setString(4, phone);
            ps.setInt(5, farmerId);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "✅ Farmer updated successfully!");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void deleteFarmer() {
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Search for a farmer first!");
            return;
        }

        int farmerId = (int) model.getValueAt(0, 0);
        String name = model.getValueAt(0, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
            "⚠️ Are you sure you want to delete\nFarmer ID: " + farmerId + " - " + name + "?\n\nThis will also delete all their tree records!",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            Connection con = DBConnection.getConnection();

            // Delete trees first (foreign key)
            String deleteTree = "DELETE FROM Tree WHERE farmer_id = ?";
            PreparedStatement ps1 = con.prepareStatement(deleteTree);
            ps1.setInt(1, farmerId);
            ps1.executeUpdate();

            // Then delete farmer
            String deleteFarmer = "DELETE FROM Farmer WHERE farmer_id = ?";
            PreparedStatement ps2 = con.prepareStatement(deleteFarmer);
            ps2.setInt(1, farmerId);
            ps2.executeUpdate();

            model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "✅ Farmer and their trees deleted successfully!");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void updateRecord() {
        updateFarmer();
    }

    private void deleteRecord() {
        deleteFarmer();
    }

    private void viewDetails() {
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Search for a farmer first!");
            return;
        }
        int farmerId = (int) model.getValueAt(0, 0);
        StringBuilder details = new StringBuilder("FARMER DETAILS\n");
        for (int i = 0; i < 40; i++) details.append("─");
        details.append("\n");
        for (int i = 0; i < model.getColumnCount(); i++) {
            details.append(model.getColumnName(i)).append(": ");
            details.append(model.getValueAt(0, i)).append("\n");
        }
        JOptionPane.showMessageDialog(this, details.toString(), "Farmer Details", JOptionPane.INFORMATION_MESSAGE);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateDelete().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
