/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saniy
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
public class ViewData extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewData.class.getName());

    /**
     * Creates new form ViewData
     */
    public ViewData() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void loadData() {
        setTitle("📊 View All Records");
        setSize(1200, 750);
        setLocationRelativeTo(null);
        setLayout(null);
        getContentPane().setBackground(new Color(245, 250, 245));
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // ===== HEADER PANEL =====
        JPanel headerPanel = new JPanel();
        headerPanel.setBounds(0, 0, 1200, 90);
        headerPanel.setBackground(new Color(34, 100, 34));
        headerPanel.setLayout(null);
        add(headerPanel);

        JLabel title = new JLabel("📊 All Records Database");
        title.setFont(new Font("Arial", Font.BOLD, 26));
        title.setForeground(Color.WHITE);
        title.setBounds(20, 10, 400, 35);
        headerPanel.add(title);

        JLabel subtitle = new JLabel("View all tree planting and farmer records in the system");
        subtitle.setFont(new Font("Arial", Font.ITALIC, 12));
        subtitle.setForeground(new Color(200, 255, 200));
        subtitle.setBounds(20, 50, 500, 25);
        headerPanel.add(subtitle);

        // ===== TABLE PANEL =====
        JPanel tablePanel = new JPanel();
        tablePanel.setBounds(20, 100, 1160, 550);
        tablePanel.setBackground(Color.WHITE);
        tablePanel.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 2));
        tablePanel.setLayout(new BorderLayout());
        add(tablePanel);

        String[] columns = {"Tree ID", "Farmer ID", "Tree Type", "Plant Date", "Latitude", "Longitude", "Status"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Read-only
            }
        };

        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT t.*, f.name FROM Tree t JOIN Farmer f ON t.farmer_id = f.farmer_id ORDER BY t.plant_date DESC";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("tree_id"),
                    rs.getInt("farmer_id"),
                    rs.getString("tree_type"),
                    rs.getDate("plant_date"),
                    String.format("%.4f", rs.getDouble("latitude")),
                    String.format("%.4f", rs.getDouble("longitude")),
                    rs.getString("status")
                };
                model.addRow(row);
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Error loading data", e);
        }

        JTable table = new JTable(model);
        table.setRowHeight(25);
        table.getTableHeader().setBackground(new Color(34, 139, 34));
        table.getTableHeader().setForeground(Color.WHITE);
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        table.setFont(new Font("Arial", Font.PLAIN, 11));
        table.setSelectionBackground(new Color(184, 207, 229));
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        JScrollPane scroll = new JScrollPane(table);
        tablePanel.add(scroll, BorderLayout.CENTER);

        // ===== ACTION PANEL =====
        JPanel actionPanel = new JPanel();
        actionPanel.setBounds(20, 660, 1160, 50);
        actionPanel.setBackground(new Color(240, 245, 240));
        actionPanel.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1));
        actionPanel.setLayout(null);
        add(actionPanel);

        JButton btnExport = new JButton("💾 Export CSV");
        btnExport.setBounds(20, 10, 120, 30);
        btnExport.setBackground(new Color(0, 100, 200));
        btnExport.setForeground(Color.WHITE);
        btnExport.setFont(new Font("Arial", Font.BOLD, 11));
        btnExport.setFocusPainted(false);
        btnExport.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnExport.addActionListener(e -> exportToCSV());
        actionPanel.add(btnExport);

        JButton btnRefresh = new JButton("🔄 Refresh");
        btnRefresh.setBounds(150, 10, 120, 30);
        btnRefresh.setBackground(new Color(34, 139, 34));
        btnRefresh.setForeground(Color.WHITE);
        btnRefresh.setFont(new Font("Arial", Font.BOLD, 11));
        btnRefresh.setFocusPainted(false);
        btnRefresh.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(e -> {
            dispose();
            new ViewData().setVisible(true);
        });
        actionPanel.add(btnRefresh);

        JButton btnClose = new JButton("❌ Close");
        btnClose.setBounds(1020, 10, 120, 30);
        btnClose.setBackground(new Color(100, 100, 100));
        btnClose.setForeground(Color.WHITE);
        btnClose.setFont(new Font("Arial", Font.BOLD, 11));
        btnClose.setFocusPainted(false);
        btnClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClose.addActionListener(e -> dispose());
        actionPanel.add(btnClose);

        JLabel statsLabel = new JLabel("📊 Total: " + model.getRowCount() + " records | Showing all trees sorted by latest first");
        statsLabel.setFont(new Font("Arial", Font.ITALIC, 10));
        statsLabel.setForeground(new Color(100, 100, 100));
        statsLabel.setBounds(280, 15, 700, 20);
        actionPanel.add(statsLabel);
    }

    private void exportToCSV() {
        try {
            String filename = "GreenLedger_Export_" + java.time.LocalDate.now() + ".csv";
            java.io.FileWriter fw = new java.io.FileWriter(filename);
            
            fw.write("Tree ID,Farmer ID,Tree Type,Plant Date,Latitude,Longitude,Status\n");
            
            Connection con = DBConnection.getConnection();
            String sql = "SELECT t.*, f.name FROM Tree t JOIN Farmer f ON t.farmer_id = f.farmer_id ORDER BY t.plant_date DESC";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                fw.write(
                    rs.getInt("tree_id") + "," +
                    rs.getInt("farmer_id") + "," +
                    rs.getString("tree_type") + "," +
                    rs.getDate("plant_date") + "," +
                    rs.getDouble("latitude") + "," +
                    rs.getDouble("longitude") + "," +
                    rs.getString("status") + "\n"
                );
            }
            
            fw.close();
            con.close();
            JOptionPane.showMessageDialog(this, 
                "✅ Exported successfully!\nFile: " + filename, "Export", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new ViewData().setVisible(true));
    }
}
